### ISSUE TITLE
LibUWS and LibHTGS_VISUALIZER errors with cmake

### ISSUE THREAD

**Issue by nategarver-daniels** [usnistgov/HTGS#2]
Hello.  We are having a small problem getting cmake to generate the makefiles.  I've installed libUV, but I get the following errors:
-- Could NOT find LibUWS (missing:  LIBUWS_LIBRARY LIBUWS_INCLUDE_DIR) 
-- Could NOT find LibUWS (missing:  LIBUWS_LIBRARY LIBUWS_INCLUDE_DIR) 
-- Could NOT find LibHTGS_VISUALIZER (missing:  LIBHTGS_VISUALIZER_LIBRARY LIBHTGS_VISUALIZER_INCLUDE_DIR) 
CMake Error: The following variables are used in this project, but they are set to NOTFOUND.
Please set them or make sure they are set and tested correctly in the CMake files:
LIBHTGS_VISUALIZER_INCLUDE_DIR (ADVANCED)
   used as include directory in directory /opt/pulsar/src/HTGS/src
LIBHTGS_VISUALIZER_LIBRARY (ADVANCED)
    linked by target "main" in directory /opt/pulsar/src/HTGS/src
LIBUWS_INCLUDE_DIR (ADVANCED)
   used as include directory in directory /opt/pulsar/src/HTGS/src
LIBUWS_LIBRARY (ADVANCED)
    linked by target "main" in directory /opt/pulsar/src/HTGS/src

and the rule file in cmake-modules is a bit confusing, as it references libUV in the section about libUWS and is looking for uWS.h, etc.  I've not been able to determine what linux package might supply uWS.  Thanks!

**Comment by tblattner** [comment]
Hello,

Just checked things out and I had mistakenly set "HTGSVisualizer to REQUIRED". 

For the time being I have commented out the find_package(HTGSVisualizer QUIET). 

We are currently testing visualizing the graph via HTML5 + web sockets in real-time. This is in active development, but will hopefully be available sometime this summer or in the fall.

Sorry about that.

Let me know if this resolves your issue.

Regards,
Tim

**Comment by nategarver-daniels** [comment]
No worries.  That took care of the problem.  Thanks!
